version: 0.2
env:

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm cache clean --force
      - npm install -g @angular/cli
      - npm install --save-dev @angular-devkit/build-angular

  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
     commands:
     - echo Build completed on `date`
     
artifacts:
  files:
      - '**/*'
  base-directory: dist/angular-app
  discard-paths: yes